version: '3.4'

services:
  postgres:
    image: 'postgres:13.6-alpine'
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  app:
    tty: true
    stdin_open: true
    build: .
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432"
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres
      - redis

volumes:
  postgres:
  redis:
